name: edgex-device-rest
base: core18
type: app
adopt-info: version
license: Apache-2.0
title: EdgeX REST Device Service
summary: EdgeX device service for REST protocol
description: |
  This device service provides easy way for 3'rd party applications, 
  such as Point of Sale, CV Analytics, etc., to push data into EdgeX 
  via the REST protocol.

# delhi: 0, edinburgh: 1, fuji: 2, geneva: 3, ireland: 4
epoch: 4

# TODO: add armhf here when that's supported
architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict

apps:
  device-rest:
    adapter: none
    command: bin/device-rest $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/startup-env-var.sh
    daemon: simple
    environment:
      CONFIG_PRO_ARG: "--cp=consul://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-rest/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-rest/res"
    plugs: [network, network-bind]

parts:
  version:
    plugin: nil
    source: snap/local
    override-pull: |
      cd $SNAPCRAFT_PROJECT_DIR
      if [ -f VERSION ]; then
        PROJECT_VERSION=$(cat VERSION)
      else
        PROJECT_VERSION="0.0.0"
      fi
      snapcraftctl set-version ${PROJECT_VERSION}

  device-rest:
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    build-snaps:
      - go/1.16/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      go mod tidy
      make build

      install -DT "./cmd/device-rest" "$SNAPCRAFT_PART_INSTALL/bin/device-rest"

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-rest/res/"

      cat "./cmd/res/configuration.toml" | \
        sed -e s:"'./device-rest.log'":"'\$SNAP_COMMON/device-rest.log'": \
        -e s:"ProfilesDir = './res/profiles'":"ProfilesDir = '\$SNAP_DATA/config/device-rest/res/profiles'":  \
        -e s:"DevicesDir = './res/devices'":"DevicesDir = '\$SNAP_DATA/config/device-rest/res/devices'": > \
        "$SNAPCRAFT_PART_INSTALL/config/device-rest/res/configuration.toml"

      for fpath in ./cmd/res/profiles/*.yaml; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/profiles/${fname}" \
          "$SNAPCRAFT_PART_INSTALL/config/device-rest/res/profiles/${fname}"
      done

      for fpath in ./cmd/res/devices/*.toml; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/devices/${fname}" \
          "$SNAPCRAFT_PART_INSTALL/config/device-rest/res/devices/${fname}"
      done

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rest/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-rest/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers
